name:                LimitCalc
version:             0.1.0.0
github:              "githubuser/LimitCalc"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/LimitCalc#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1.11 && < 4
- scotty

library:
  source-dirs: src
  exposed-modules:
  - LimitCalc
  - LimitCalc.Expr
  - LimitCalc.Limits
  - LimitCalc.Parsing
  ghc-options:
  - -Wno-simplifiable-class-constraints

executables:
  LimitServer:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LimitCalc

tests:
  limits:
    main:                Runner.hs
    source-dirs:
    - test/runners/limits
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - LimitCalc
  limits-basic:
    main:                Runner.hs
    source-dirs:
    - test
    - test/runners/limits/basic
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LimitCalc
    - hspec
  limits-unstable:
    main:                Runner.hs
    source-dirs:
    - test
    - test/runners/limits/unstable
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LimitCalc
    - hspec
  parser:
    main:                Runner.hs
    source-dirs:
    - test/runners/parser
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
